# Generated by Django 4.2.5 on 2023-09-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='title',
        ),
    ]
